# Parameters for the 1D sticks lattice. There parameters defined below are the
# paramters that can be set by the user. The other parameters are set by the
# program and should not be changed.
#
# box: Parameters related to the box.
#     position_top: The position of the top of the box. The bottom of the box is
#      calculated from the box width and height.
#     height: The height of the box; must be a positive number.
#     width: The width of the box; must be a positive number.
# box_label: The parameters related to the label of the box.
#     height: The height of the box label; must be a positive number and less
#      than the box height.
#     width: The width of the box label; must be a positive number and less than
#      the box width.
# lattice: The parameters related to the basic lattice configuration.
#     offsets: The offsets of where the ticks will initially be drawn; must be
#      an array of positive numbers.
#     position_end: The position of the end of the base of the lattice; must be
#      a positive number.
#     position_start: The position of the start of the base of the lattice; must
#      be a positive number.
#     vertical_spacing: The vertical spacing between lattice elements; must be a
#      positive number.
# lattice_elements: The parameters related to the lattice elements.
#     arrow_height: The length of the adsorption/desorption arrows; must be a
#      positive number.
#     circle_radius: The radius of the circles that represent the particles;
#      must be a positive number.
#     tick_height: The length of the lattice ticks; must be a positive number.
#     vacancies_visible: A boolean flag indicating whether the vacancies should
#      be visible or not. True, if the vacancies should be visible; False,
#      otherwise.
# lattice_parameters: The parameters related to the lattice parameters.
#     nticks: The number of ticks in the lattice; must be a positive integer
#      number.
#     adsorbing: An array of integer integer numbers indicating the ticks that
#      contain adsorbing particles.
#     desorbing: An array of integer integer numbers indicating the ticks that
#      contain desorbing particles.
#     fixed: An array of integer numbers indicating the ticks that contain fixed
#      particles.
#     jumping: An array of arrays of 3 integers, where the first element
#      indicates the tick where the particle is jumping from, the second element
#      indicates the number of spaces the particle is jumping to the left and
#      the third element indicates the number of spaces the particle is jumping
#      to the right. The number of spaces must be a positive integer number and
#      the jump must be performed to a place in the lattice.
box:
  position_top: [ 0, 0 ]
  height: 15.0
  width: 15.0
box_label:
  height: 2.0
  width: 2.0
lattice:
  offsets: [ 0.0, 0.0 ]
  position_end: [ 14.0, 9.0 ]
  position_start: [ 1.0, 9.0 ]
  vertical_spacing: 0.5
lattice_elements:
  arrow_height: 3.0
  circle_radius: 0.75
  tick_height: 3.0
  vacancies_visible: True
lattice_parameters:
  nticks: 10
  adsorbing: [ ]
  desorbing: [ ]
  fixed: [ ]
  jumping: [ ]